version: '3'

# Runs the explorer
#
# make testnet OR make sh-testnet
# then:
# docker compose up

services:
  pingpub:
    image: pingpub:latest
    network_mode: "host"
    build:
      context: explorer
      dockerfile: ./Dockerfile

    volumes:
      - ./explorer/chains:/app/chains/
    ports:
      - "80:80"
      - "443:443"
